### ISSUE TITLE
Travis: Use Node.js 8

### ISSUE THREAD

**Issue by azu** [almin/almin#307]
Node.js 8 is LTS.
We want to move to Node.js 8 on Travis CI.

https://github.com/almin/almin/blob/fe73ae82ed7e6ad8c92b4d1dee702af53d1ab920/.travis.yml#L4

**Comment by teppeis** [comment]
@azu This is fixed in https://github.com/almin/almin/commit/0b4f568db3456be5952e53f3f708285062618940#diff-354f30a63fb0907d4ad57269548329e3

**Comment by azu** [comment]
Yes! Thanks for the heads up.

Closing...
