### ISSUE TITLE
Render props for Almin + React

### ISSUE THREAD

**Issue by azu** [almin/almin#318]
We already have `almin-react-container` that is HOC component for react.
Recently, react add new document about Render Props

- [Render Props - React](https://reactjs.org/docs/render-props.html "Render Props - React")

It will help to write react container component.

## Motivation

It is difficult to type component for HOC.

https://github.com/almin/almin/blob/87e15d87bfc5a3d73af4d20799e0041128ece6cd/packages/almin-react-container/src/almin-react-container.tsx#L7-L23

The maintainability of that typing is not good.

## Related

- [Render props version of connect · Issue #799 · reactjs/react-redux](https://github.com/reactjs/react-redux/issues/799)
- [jsonnull/redux-render: Ergonomic Redux bindings for React using render functions](https://github.com/jsonnull/redux-render)
- [Connecting React component to Redux store with render callback](https://medium.com/netscape/connecting-react-component-to-redux-store-with-render-callback-53fd044bb42b)
- [New API to match context RFC by mjackson · Pull Request #47 · ReactTraining/react-broadcast](https://github.com/ReactTraining/react-broadcast/pull/47 "New API to match context RFC by mjackson · Pull Request #47 · ReactTraining/react-broadcast")

**Comment by koba04** [comment]
React's new context API might adopt the render props pattern.

https://github.com/reactjs/rfcs/pull/2

This discussion in the RFC might be useful for this proposal. It's a very long threads though😅

> It is difficult to type component for HOC.

I agree with you.
Unfortunately, In addition to that, flowtype has some issues related typing with HOC.

https://github.com/facebook/flow/issues/4709

**Comment by azu** [comment]
Thanks for suggestion :)

**Comment by azu** [comment]
Instersting approach

https://github.com/thejameskyle/unstated

**Comment by azu** [comment]
Image(I do not try to implement this image yet...)

```jsx
import { StoreGroup, Context } from "almin";
const storeGroup = new StoreGroup({
  app: new AppStore(),
  counter: new CounterStore();
});

const context = new Context({ store: storeGroup });

function Counter() {
  return (
    <Subscribe to={[AppStore, CounterStore]}>
      {(app, counter) => (
        <div>
          <span>Count: {counter.state.count}</span>
          <button onClick={() => counter.decrement(app.state.amount)}>-</button>
          <button onClick={() => counter.increment(app.state.amount)}>+</button>
        </div>
      )}
    </Subscribe>
  );
}

function App() {
  return (
    <Subscribe to={[AppStore]}>
      {app => (
        <div>
          <Counter />
          <label>Amount: </label>
          <input
            type="number"
            value={app.state.amount}
            onChange={event => {
              context.useCase(new IncrementUseCase()).execute();
            }}
          />
        </div>
      )}
    </Subscribe>
  );
}

render(
  <Provider context={context}>
    <App />
  </Provider>,
  window.complex
);
```

**Comment by azu** [comment]
Article: [React’s ⚛️ new Context API – DailyJS – Medium](https://medium.com/dailyjs/reacts-%EF%B8%8F-new-context-api-70c9fe01596b "React’s ⚛️ new Context API – DailyJS – Medium")

**Comment by azu** [comment]
https://github.com/bvaughn/react/tree/create-component-with-subscriptions/packages/create-subscription

**Comment by azu** [comment]
Related Context API based design::

* [React 16 experiment: rewrite React-Redux to use new context API by markerikson · Pull Request #898 · reactjs/react-redux](https://github.com/reactjs/react-redux/pull/898 "React 16 experiment: rewrite React-Redux to use new context API by markerikson · Pull Request #898 · reactjs/react-redux")
* [jamiebuilds/unstated: State so simple, it goes without saying](https://github.com/jamiebuilds/unstated "jamiebuilds/unstated: State so simple, it goes without saying")
* [Refactor with new React Context API · Issue #448 · mobxjs/mobx-react](https://github.com/mobxjs/mobx-react/issues/448 "Refactor with new React Context API · Issue #448 · mobxjs/mobx-react")

**Comment by azu** [comment]
Implemented [@almin/react-context](https://github.com/almin/almin/tree/master/packages/%40almin/react-context)
