### ISSUE TITLE
Almin 0.10 Roadmap

### ISSUE THREAD

**Issue by azu** [almin/almin#67]
Next release is 0.10.

## Breaking Changes

- #62 #61 Introduce `meta` for dispatcher

**0.9**:

```js
context.onWillExecuteEachUseCase(payload => {
    console.log(payload.args, payload.useCase);
});
context.onDidExecuteEachUseCase(payload => {
    console.log(payload.value, payload.useCase);
});
context.onCompleteEachUseCase(payload=> {
    console.log(payload.value, payload.useCase);
});
context.onErrorDispatch(payload => {
    console.log(payload.error);
});
context.onDispatch(payload => {
    console.log(payload.type);
});
```

**0.10**:

You can get `useCase` via `meta` object.

```js
context.onWillExecuteEachUseCase((payload: WillExecutedPayload, meta: DispatcherPayloadMeta) => {
    console.log(payload.args, meta);
});
context.onDidExecuteEachUseCase((payload: DidExecutedPayload, meta: DispatcherPayloadMeta) => {
    console.log(payload.value, meta);
});
context.onCompleteEachUseCase((payload: CompletedPayload, meta: DispatcherPayloadMeta) => {
    console.log(payload.value, meta);
});
context.onErrorDispatch((payload: ErrorPayload, meta: DispatcherPayloadMeta) => {
    console.log(payload.error, meta);
});
context.onDispatch((payload: Payload, meta: DispatcherPayloadMeta) => {
    console.log(payload.type, meta);
});
```

- #64 Store#onError is depreacted
  - You can use `UseCase#dispatch` insteadof it.
- #68 Convert to TypeScript
- #81 #80 `Store#onChange(cb: (hangingStores: Array<StoreLike>) => void): () => void {}`
  - `StoreGroup` is not changed. This affect the user that use directly `Store` class.
- #87 #86 Remove `***Payload.Type` static property
- #94 **Internal**: use named exports insteadof default exports
- #93 Update Flow definition
- almin-logger should support 0.10(curret master).

## Documentation

- #65 #97 Update Documentation

## Blockers

- #90 API Reference (It can put back)

## Closes at releases

- #55

**Comment by saneyuki** [comment]
> Breaking Change

add: https://github.com/almin/almin/pull/94

**Comment by azu** [comment]
https://github.com/almin/almin/releases/tag/0.10.0-1
New pre-release

**Comment by azu** [comment]
#113 I've checked benchmark.
0.10@beta is faster than 0.9.

We will release 0.10 stable at current~next week.

**Comment by azu** [comment]
We've released https://github.com/almin/almin/releases/tag/0.10.0 🎉 
Also, update https://github.com/almin/almin-logger/releases/tag/4.0.0 and examples #114

**Comment by azu** [comment]
I close it.

We will continute to inverstigate documentation issue # #90 and TypeScript issues #81 #89 #107
