### ISSUE TITLE
TypeScript: StoreGroup#getState interface

### ISSUE THREAD

**Issue by azu** [almin/almin#71]
From #68 

```diff
+    getState<T>(): T {
+        return (this._storeGroup as any).getState(); // TODO: remove casting `any`
```

> @saneyuki said
> I thought to introduce some new interfaces which is implemented by StoreGroup or Store to fix it.
> Perhaps is it not a right way?

We should resolve this TODO issue.

**Comment by saneyuki** [comment]
- This has been fixed by https://github.com/almin/almin/pull/80
- Rest works is handled by https://github.com/almin/almin/issues/81

**Comment by azu** [comment]
pin #80
