### ISSUE TITLE
TypeScript-Babel: jsdoc-to-assert is not working

### ISSUE THREAD

**Issue by azu** [almin/almin#82]
>  "build:down_transform": "NODE_ENV=production babel __obj --out-dir lib --source-maps",

and

jsdoc-to-assert is setup in `NODE=ENV=development`.

and

JSDoc's type is removed in #68 

It is not working. 

Should we remove this from `.babelrc`?

**Comment by saneyuki** [comment]
> Should we remove this from .babelrc?

How about https://github.com/almin/almin/issues/83? We might be able to re-enable power-assert

**Comment by azu** [comment]
> re-enable power-assert

Looks good to me.
