### ISSUE TITLE
Sort the type of UseCaseContext's constructor

### ISSUE THREAD

**Issue by saneyuki** [almin/almin#85]
## env

- source: https://github.com/almin/almin/tree/486ebcde40478523f8694df789cc97960c22da6a

## Problem

1. There are inconsistency:
    - [By JSDoc comment](https://github.com/almin/almin/blob/486ebcde40478523f8694df789cc97960c22da6a/src/UseCaseContext.ts#L19), `dispatcher` argument of `UseCaseContext.constructor` should be an optional argument.
    - [By the document](https://github.com/almin/almin/tree/486ebcde40478523f8694df789cc97960c22da6a/docs/api#constructordispatcher-dispatcher--usecase), `dispatcher` argument of `UseCaseContext.constructor` should be `UseCase | Dispatcher`.
2. If we sort the code with JSDoc annotation, there is the conflict with [UseCaseExecutorArgs](https://github.com/almin/almin/blob/486ebcde40478523f8694df789cc97960c22da6a/src/UseCaseExecutor.ts).
2. If we sort the code with the document, there is the conflict with [UseCaseExecutorArgs.parent](https://github.com/almin/almin/blob/486ebcde40478523f8694df789cc97960c22da6a/src/UseCaseExecutor.ts).

So which is the correct way?

**Comment by azu** [comment]
`UseCaseContext` need a `UseCase` instance  as constructor arguments.

- https://github.com/almin/almin/blob/486ebcde40478523f8694df789cc97960c22da6a/src/UseCase.ts#L76-L78

```ts
    constructor(dispatcher: UseCase) {
        this.dispatcher = dispatcher;
    }
```

is correct.
