### ISSUE TITLE
Really need ***Payload.Type as static property?

### ISSUE THREAD

**Issue by saneyuki** [almin/almin#86]
1. These are used to check the type of them.
2. However, by https://github.com/almin/almin/pull/79, we can use the type guard function to check it.
3. To get the "tag" string to define a type, we can use `TYPE` via import for each modules by https://github.com/almin/almin/pull/68
4. By these thing, Do we really need `***Payload.Type` as static property?

**Comment by azu** [comment]
> Do we really need ***Payload.Type as static property?

@saneyuki Short answer is, No.
I think that Each `TYPE` is private value.
But, We already know that internal constant value(we think) is not truly private.

- [Anti-pattern: reacting to @@INIT action · Issue #186 · reactjs/redux](https://github.com/reactjs/redux/issues/186)
- [Question: why does the init action @@redux/INIT is being twice? · Issue #382 · reactjs/redux](https://github.com/reactjs/redux/issues/382)

We can make it secure by removing `***Payload.TYPE` getter.
