### ISSUE TITLE
Update Flowtype definitions of this project.

### ISSUE THREAD

**Issue by saneyuki** [almin/almin#93]
Our repository has [the type definitions for Flowtype](https://github.com/almin/almin/blob/master/type-definitions/almin.js.flow). This should be updated to the latest interface.

**Comment by azu** [comment]
Yes.
This changes should be waited for decision of #85 and  #91

I've updated summary of these change in

- [Almin 0.10 Roadmap · Issue #67 · almin/almin](https://github.com/almin/almin/issues/67 "Almin 0.10 Roadmap · Issue #67 · almin/almin")

/cc @yamadayuki
